### ISSUE TITLE
Step 2 bug

### ISSUE THREAD

**Issue by cmilica** [gitter-lab/ml4bio#26]
I thought this might be the best place to note this so I make sure I don't forget.

I think I found a bug... When you are on step 2: Train Classifiers, you can name each classifier. You can train the same classifier as many time as you want, with the same hyperparameters but different names, or no names at all. 
However, if you try naming a classifier the name that was already given to another classifier, Step 2 completely grays out and you can't do anything anymore. 
You can go to Step 3 and go to Finish. Then you will be asked if you want to load more data. If you click yes, and then load the new data again and go to Step 2, this step is still greyed out. The only thing to do is reopen the ml4bio again.

To reproduce:
- load the data and go to Step 2
- train any classifier and name it anything
- train another classifier and give it the same name

**Comment by agitter** [comment]
Good discovery.  I can reproduce this following your instructions.

Is our desired behavior that step 2 is not disabled after giving an existing classifier name?  I would expect that it should be possible to choose a new name and then continue trainin.

**Comment by cmilica** [comment]
Yes, I would say there should be an error message, but once the name is changed we should be able to continue.
