### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by agitter** [gitter-lab/ml4bio#3]

**Comment by agitter** [comment]
@fmu2 are there any immediate software changes or bug fixes we need to make before uploading version 0.1.0 to PyPI?  I'd like to have a initial version available to reserve the `ml4bio` package name and make the installation easier.

I looked at https://github.com/gitter-lab/ml-bio-workshop/issues/7 and https://github.com/gitter-lab/ml-bio-workshop/issues/14.  The suggestion to ` Clear the unlabeled data after loading a new labeled dataset` is the only one that we may want to include in this initial release.

Also, do you want to upload to PyPI or should I do it?  One of us needs to create a user account to do so.  I don't mind doing it so that I can maintain the package long term, but I will leave you as the author.

**Comment by fmu2** [comment]
@agitter I fixed the following problem:
a) clear the unlabeled data after loading new labeled data
b) links to icons
c) warn users that trained classifiers will be cleared if they click 'return' on the 2nd page

I would prefer you uploading the package to PyPI so it can be better taken care of in the long run and can be more easily shared with other students in the lab.

**Comment by agitter** [comment]
I uploaded the initial version to PyPI and also tagged and released it on GitHub:
https://pypi.org/project/ml4bio/
https://github.com/gitter-lab/ml4bio/releases/tag/v0.1.0

We can update the version number when we are ready to upload a new version.
